// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1OxqNlbUUCrnUEztiXy30r3OWPtUUoo',
    appId: '1:153061740439:web:b0febab4ff5d4f2e78bed2',
    messagingSenderId: '153061740439',
    projectId: 'thimar-24257',
    authDomain: 'thimar-24257.firebaseapp.com',
    storageBucket: 'thimar-24257.appspot.com',
    measurementId: 'G-94LTF08M81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5erWzUYwZw_MJtYq9MzxzQ6lEQGsl4M',
    appId: '1:153061740439:android:ed7fac1dd94ddfe878bed2',
    messagingSenderId: '153061740439',
    projectId: 'thimar-24257',
    storageBucket: 'thimar-24257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4G40wvd72a_8asfU_y6xa8B42R0a4H1U',
    appId: '1:153061740439:ios:cf6987347de1075678bed2',
    messagingSenderId: '153061740439',
    projectId: 'thimar-24257',
    storageBucket: 'thimar-24257.appspot.com',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4G40wvd72a_8asfU_y6xa8B42R0a4H1U',
    appId: '1:153061740439:ios:9ef0e55ced5f64f878bed2',
    messagingSenderId: '153061740439',
    projectId: 'thimar-24257',
    storageBucket: 'thimar-24257.appspot.com',
    iosBundleId: 'com.example.thimar.RunnerTests',
  );
}
